# Generated by Django 4.1.4 on 2022-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='upload_media/sites/category/shablon.jpg', upload_to='upload_media/sites/category/image/'),
        ),
    ]
